package net.thunderbird.feature.mail.message.classification.api

/**
 * What kind of mail a message is, for the purpose of deciding how prominently to present it.
 *
 * The classes are about who sent the message and why, not about whether it matters. A build failure and a
 * shipping confirmation are both [NOTIFICATION] even though only one is urgent.
 */
enum class MessageClass {
    /**
     * Written by a person to a small number of recipients, expecting a reply.
     *
     * The class that must not be assigned wrongly in either direction: missing it buries real correspondence,
     * and over-assigning it makes the whole feature pointless.
     */
    HUMAN,

    /** Generated by a system: receipts, alerts, password resets, reports. */
    NOTIFICATION,

    /** Sent in bulk to many recipients: marketing, digests, mailing lists. */
    NEWSLETTER,

    /**
     * Not enough evidence to say.
     *
     * A first-class outcome rather than a failure. Most mail carries no positive evidence of being written by
     * a person, so guessing here would be guessing against the class we can least afford to get wrong.
     */
    UNKNOWN,
}

/**
 * The evidence that decided a classification.
 *
 * Stored alongside the class so a surprising verdict can be explained to the user and debugged by us. Without
 * it, changing the rules later means re-deriving why every message landed where it did.
 */
enum class ClassificationSignal {
    /** Nothing fired. */
    NONE,

    /** `List-Id` or `List-Post`: a genuine mailing list, as opposed to a marketing send. */
    MAILING_LIST,

    /** `Auto-Submitted` other than `no`, per RFC 3834. */
    AUTO_SUBMITTED,

    /** `X-Auto-Response-Suppress`: the sender is declaring it will not read replies. */
    AUTO_RESPONSE_SUPPRESSED,

    /** `List-Unsubscribe` or `Precedence: bulk`/`list`. */
    BULK_HEADER,

    /** The sender address is one of the conventional do-not-reply forms. */
    NO_REPLY_SENDER,

    /**
     * A rule the user taught, by correcting a message from this sender or domain.
     *
     * Outranks every header rule. The headers describe how a sender chose to label itself; this describes
     * what the mail actually is to the person reading it, and when the two disagree the reader is right.
     */
    USER_OVERRIDE,
}

/**
 * A verdict and the reason for it.
 */
data class MessageClassification(
    val messageClass: MessageClass,
    val signal: ClassificationSignal,
) {
    companion object {
        val UNKNOWN = MessageClassification(MessageClass.UNKNOWN, ClassificationSignal.NONE)
    }
}

/**
 * The version of the rules that produced a classification.
 *
 * Stored with each verdict so a later improvement can tell which messages predate it. Version 2 recognises a
 * do-not-reply marker anywhere in the sender's local part, not only at the start.
 */
const val CLASSIFIER_VERSION: Int = 2
